---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.3.3.0

branches:
  only:
    - master

before_install:
  - sudo apt-get update -y

install:
  # Make upper directory as role_path for ansible
  - dir=$(pwd) && printf "[defaults]\nroles_path = $(dirname $dir)" > ansible.cfg

  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

  # Install role dependencies
  - ansible-galaxy install -r requirements.yml --roles-path ../

script:
  # Check the playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the playbook with ansible-playbook without TLS.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvvv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
